version: 2.1

orbs:
  docker: circleci/docker@2.0.3

workflows:
  build-and-publish:
    jobs:
      - docker/publish:
        image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
        update-description: true
